import SwiftUI

/// A small 3D picture for an item ("milk", "AA batteries", "birthday candles"), from
/// Microsoft's Fluent Emoji (MIT license). Items without a match get no picture at all,
/// so callers simply show nothing in that spot.
enum ItemIcon {
    /// The asset name in Assets.xcassets/ItemIcons for a search or list item, or nil.
    static func assetName(for text: String) -> String? {
        let words = normalize(text).split(separator: " ").map(String.init)
        guard !words.isEmpty else { return nil }
        if let cached = cache[words.joined(separator: " ")] { return cached }
        var found: String?
        // Longest phrase first, so "chocolate milk" beats "milk" and "peanut butter" beats "butter".
        search: for length in stride(from: min(4, words.count), through: 1, by: -1) {
            // Later words usually name the thing ("organic whole milk"), so scan from the end.
            for start in stride(from: words.count - length, through: 0, by: -1) {
                let phrase = words[start..<start + length].joined(separator: " ")
                if let slug = lookup(phrase) {
                    found = slug
                    break search
                }
            }
        }
        let name = found.map { "ItemIcons/\($0)" }
        cache[words.joined(separator: " ")] = name
        return name
    }

    private static var cache: [String: String?] = [:]

    private static func normalize(_ text: String) -> String {
        let lowered = text.lowercased()
            .replacingOccurrences(of: "&", with: " and ")
            .replacingOccurrences(of: "-", with: " ")
        let kept = lowered.unicodeScalars.map { CharacterSet.alphanumerics.contains($0) || $0 == " " || $0 == "%" ? Character($0) : " " }
        return String(kept).split(separator: " ").joined(separator: " ")
    }

    /// Exact phrase, then simple singular forms ("berries" → "berry", "boxes" → "box", "eggs" → "egg").
    private static func lookup(_ phrase: String) -> String? {
        if let hit = keywords[phrase] { return hit }
        var candidates: [String] = []
        if phrase.hasSuffix("ies") { candidates.append(String(phrase.dropLast(3)) + "y") }
        if phrase.hasSuffix("es") { candidates.append(String(phrase.dropLast(2))) }
        if phrase.hasSuffix("s") { candidates.append(String(phrase.dropLast())) }
        candidates.append(phrase + "s")
        for candidate in candidates {
            if let hit = keywords[candidate] { return hit }
        }
        return nil
    }

    /// Search words → icon. Add more freely; several words can share one icon.
    static let keywords: [String: String] = [
        "2% milk": "glass-of-milk",
        "9v battery": "battery",
        "aa batteries": "battery",
        "aaa batteries": "battery",
        "adapter": "electric-plug",
        "advil": "pill",
        "agave": "honey-pot",
        "ale": "beer-mug",
        "allergy medicine": "pill",
        "almond milk": "glass-of-milk",
        "almonds": "peanuts",
        "apple": "red-apple",
        "apple juice": "beverage-box",
        "apples": "red-apple",
        "applesauce": "green-apple",
        "apricot": "peach",
        "arugula": "leafy-green",
        "aspirin": "pill",
        "avocado": "avocado",
        "avocados": "avocado",
        "baby": "baby-bottle",
        "baby bottle": "baby-bottle",
        "baby carrots": "carrot",
        "baby food": "baby-bottle",
        "baby formula": "baby-bottle",
        "baby wipes": "baby-bottle",
        "bacon": "bacon",
        "bag of ice": "ice",
        "bagel": "bagel",
        "bagels": "bagel",
        "baguette": "baguette-bread",
        "baked beans": "beans",
        "baking cups": "cupcake",
        "baking powder": "salt",
        "baking soda": "salt",
        "ball": "soccer-ball",
        "balloon": "balloon",
        "balloons": "balloon",
        "banana": "banana",
        "bananas": "banana",
        "band aid": "adhesive-bandage",
        "band aids": "adhesive-bandage",
        "bandages": "adhesive-bandage",
        "basil": "leafy-green",
        "basket": "basket",
        "basmati rice": "cooked-rice",
        "batteries": "battery",
        "battery": "battery",
        "beans": "beans",
        "beef": "cut-of-meat",
        "beer": "beer-mug",
        "bell pepper": "bell-pepper",
        "bells": "bell",
        "berries": "blueberries",
        "binder": "notebook",
        "birthday cake": "birthday-cake",
        "birthday candles": "birthday-cake",
        "black beans": "beans",
        "blackberries": "blueberries",
        "bleach": "sponge",
        "blueberries": "blueberries",
        "blueberry": "blueberries",
        "boba": "bubble-tea",
        "body lotion": "lotion-bottle",
        "body wash": "soap",
        "bolts": "nut-and-bolt",
        "bottled water": "cup-with-straw",
        "bouquet": "bouquet",
        "bowls": "bowl-with-spoon",
        "boxes": "package",
        "bread": "bread",
        "brie": "cheese-wedge",
        "brioche": "bread",
        "broccoli": "broccoli",
        "broom": "broom",
        "broth": "canned-food",
        "brown rice": "cooked-rice",
        "brussels sprouts": "broccoli",
        "bubble tea": "bubble-tea",
        "bucket": "bucket",
        "bulbs": "light-bulb",
        "buns": "bread",
        "burger": "hamburger",
        "burger patties": "hamburger",
        "burrito": "burrito",
        "butter": "butter",
        "buttermilk": "glass-of-milk",
        "cabbage": "leafy-green",
        "cable": "electric-plug",
        "cake": "shortcake",
        "cake mix": "shortcake",
        "candle": "candle",
        "candles": "candle",
        "candy": "candy",
        "candy bar": "chocolate-bar",
        "canned beans": "canned-food",
        "canned food": "canned-food",
        "canned goods": "canned-food",
        "canned soup": "canned-food",
        "canned tuna": "fish",
        "canned vegetables": "canned-food",
        "canola oil": "pouring-liquid",
        "cantaloupe": "watermelon",
        "capri sun": "beverage-box",
        "cards": "envelope",
        "carrot": "carrot",
        "carrots": "carrot",
        "cashews": "peanuts",
        "casserole": "shallow-pan-of-food",
        "cat": "cat",
        "cat food": "paw-prints",
        "cat litter": "paw-prints",
        "cat toys": "cat",
        "cauliflower": "broccoli",
        "celery": "leafy-green",
        "cereal": "bowl-with-spoon",
        "chai": "teacup-without-handle",
        "champagne": "bottle-with-popping-cork",
        "chapstick": "lipstick",
        "charger": "electric-plug",
        "cheddar": "cheese-wedge",
        "cheese": "cheese-wedge",
        "cheesecake": "shortcake",
        "cherries": "cherries",
        "cherry": "cherries",
        "chestnuts": "chestnut",
        "chicken": "poultry-leg",
        "chicken breast": "poultry-leg",
        "chicken thighs": "poultry-leg",
        "chicken wings": "poultry-leg",
        "chickpeas": "beans",
        "chili": "hot-pepper",
        "chili mix": "pot-of-food",
        "chili powder": "hot-pepper",
        "chilli": "hot-pepper",
        "chips": "pretzel",
        "chocolate": "chocolate-bar",
        "chocolate chips": "chocolate-bar",
        "chocolate milk": "glass-of-milk",
        "chopsticks": "chopsticks",
        "ciabatta": "baguette-bread",
        "cilantro": "leafy-green",
        "cleaner": "sponge",
        "cleaning": "sponge",
        "clementine": "tangerine",
        "cocoa": "chocolate-bar",
        "coconut": "coconut",
        "coconut milk": "coconut",
        "coconut water": "coconut",
        "cod": "fish",
        "coffee": "hot-beverage",
        "coffee beans": "hot-beverage",
        "coke": "cup-with-straw",
        "cold brew": "bubble-tea",
        "cold medicine": "pill",
        "coleslaw": "green-salad",
        "colored pencils": "pencil",
        "computer": "laptop",
        "condiments": "jar",
        "conditioner": "lotion-bottle",
        "cookie": "cookie",
        "cookies": "cookie",
        "cooking oil": "pouring-liquid",
        "corn": "ear-of-corn",
        "corn on the cob": "ear-of-corn",
        "cornmeal": "ear-of-corn",
        "cosmetics": "lipstick",
        "cottage cheese": "cheese-wedge",
        "crab": "crab",
        "crab legs": "crab",
        "crackers": "cookie",
        "crayons": "pencil",
        "cream": "glass-of-milk",
        "cream cheese": "cheese-wedge",
        "creamer": "glass-of-milk",
        "crepes": "pancakes",
        "croissant": "croissant",
        "croissants": "croissant",
        "cucumber": "cucumber",
        "cucumbers": "cucumber",
        "cup noodles": "steaming-bowl",
        "cupcake": "cupcake",
        "cupcakes": "cupcake",
        "cups": "clinking-glasses",
        "curry": "curry-rice",
        "curry paste": "curry-rice",
        "custard": "custard",
        "cuties": "tangerine",
        "cutlery": "fork-and-knife",
        "d batteries": "battery",
        "danish": "croissant",
        "deli": "sandwich",
        "deli meat": "meat-on-bone",
        "dental": "toothbrush",
        "deodorant": "lotion-bottle",
        "detergent": "soap",
        "diapers": "baby-bottle",
        "dill": "herb",
        "dish soap": "soap",
        "dishes": "fork-and-knife-with-plate",
        "dishwasher pods": "soap",
        "disinfectant": "sponge",
        "dog": "dog",
        "dog food": "paw-prints",
        "dog toys": "dog",
        "dog treats": "paw-prints",
        "donut": "doughnut",
        "donuts": "doughnut",
        "doughnut": "doughnut",
        "doughnuts": "doughnut",
        "dressing": "jar",
        "drumsticks": "poultry-leg",
        "dumplings": "dumpling",
        "dustpan": "broom",
        "earbuds": "headphone",
        "edamame": "beans",
        "egg": "egg",
        "egg whites": "egg",
        "eggplant": "eggplant",
        "eggs": "egg",
        "energy drink": "cup-with-straw",
        "envelopes": "envelope",
        "espresso": "hot-beverage",
        "extension cord": "electric-plug",
        "falafel": "falafel",
        "feta": "cheese-wedge",
        "first aid": "adhesive-bandage",
        "fish": "fish",
        "fish sticks": "fried-shrimp",
        "flan": "custard",
        "flashlight": "flashlight",
        "flatbread": "flatbread",
        "floss": "toothbrush",
        "flour": "salt",
        "flowers": "bouquet",
        "folders": "notebook",
        "forks": "fork-and-knife",
        "formula": "baby-bottle",
        "franks": "hot-dog",
        "french bread": "baguette-bread",
        "fresh herbs": "herb",
        "frosting": "shortcake",
        "frozen dinners": "bento-box",
        "frozen meals": "bento-box",
        "frozen pizza": "pizza",
        "frozen waffles": "waffle",
        "frozen yogurt": "soft-ice-cream",
        "fuji": "red-apple",
        "gala": "red-apple",
        "garbage bags": "bucket",
        "garlic": "garlic",
        "garlic bread": "baguette-bread",
        "gatorade": "cup-with-straw",
        "gelato": "ice-cream",
        "ghee": "butter",
        "gift": "wrapped-gift",
        "gift bag": "wrapped-gift",
        "gift card": "wrapped-gift",
        "gift wrap": "wrapped-gift",
        "ginger": "ginger-root",
        "glasses": "clinking-glasses",
        "gouda": "cheese-wedge",
        "graham crackers": "cookie",
        "granny smith": "green-apple",
        "granola": "bowl-with-spoon",
        "grape": "grapes",
        "grapes": "grapes",
        "greek yogurt": "bowl-with-spoon",
        "green apple": "green-apple",
        "green onions": "onion",
        "green pepper": "bell-pepper",
        "green tea": "teacup-without-handle",
        "greens": "leafy-green",
        "greeting card": "envelope",
        "groceries": "shopping-cart",
        "ground beef": "cut-of-meat",
        "ground coffee": "hot-beverage",
        "ground turkey": "cut-of-meat",
        "guacamole": "avocado",
        "gummies": "candy",
        "gummy bears": "candy",
        "gyoza": "dumpling",
        "gyro": "stuffed-flatbread",
        "half and half": "glass-of-milk",
        "ham": "meat-on-bone",
        "hamburger": "hamburger",
        "hamburger buns": "hamburger",
        "hammer": "hammer",
        "hand sanitizer": "lotion-bottle",
        "hand soap": "soap",
        "hard seltzer": "beer-mug",
        "hardware": "nut-and-bolt",
        "hash browns": "potato",
        "headphones": "headphone",
        "herbs": "leafy-green",
        "hershey": "chocolate-bar",
        "honey": "honey-pot",
        "honeycrisp": "red-apple",
        "honeydew": "watermelon",
        "hot chocolate": "hot-beverage",
        "hot dog": "hot-dog",
        "hot dog buns": "hot-dog",
        "hot dogs": "hot-dog",
        "hot sauce": "hot-pepper",
        "hummus": "falafel",
        "ibuprofen": "pill",
        "ice": "ice",
        "ice cream": "ice-cream",
        "ice cubes": "ice",
        "ice pops": "ice-cream",
        "iced coffee": "bubble-tea",
        "instant noodles": "steaming-bowl",
        "jalapeno": "hot-pepper",
        "jam": "honey-pot",
        "jar": "jar",
        "jasmine rice": "cooked-rice",
        "jello": "custard",
        "jelly": "honey-pot",
        "juice": "beverage-box",
        "juice boxes": "beverage-box",
        "k cups": "hot-beverage",
        "kale": "leafy-green",
        "kebab": "oden",
        "kefir": "glass-of-milk",
        "ketchup": "tomato",
        "kettle": "teapot",
        "kidney beans": "beans",
        "kite": "kite",
        "kiwi": "kiwi-fruit",
        "kleenex": "roll-of-paper",
        "knife": "kitchen-knife",
        "knives": "kitchen-knife",
        "lab supplies": "test-tube",
        "lager": "beer-mug",
        "lamb": "cut-of-meat",
        "laptop": "laptop",
        "lasagna": "spaghetti",
        "laundry basket": "basket",
        "laundry detergent": "soap",
        "led bulb": "light-bulb",
        "leeks": "onion",
        "lemon": "lemon",
        "lemon juice": "lemon",
        "lemonade": "lemon",
        "lemons": "lemon",
        "lentils": "beans",
        "lettuce": "leafy-green",
        "light bulb": "light-bulb",
        "light bulbs": "light-bulb",
        "lightbulb": "light-bulb",
        "lime": "lemon",
        "limes": "lemon",
        "linguine": "spaghetti",
        "lip balm": "lipstick",
        "lipstick": "lipstick",
        "liquor": "tumbler-glass",
        "loaf": "bread",
        "lobster": "lobster",
        "lollipop": "lollipop",
        "lollipops": "lollipop",
        "lotion": "lotion-bottle",
        "lunch meat": "meat-on-bone",
        "mac and cheese": "spaghetti",
        "macaroni": "spaghetti",
        "magnets": "magnet",
        "makeup": "lipstick",
        "mandarin": "tangerine",
        "mango": "mango",
        "mangoes": "mango",
        "maple syrup": "honey-pot",
        "margarine": "butter",
        "marinara": "tomato",
        "marker": "pen",
        "markers": "pen",
        "mascara": "lipstick",
        "matcha": "teacup-without-handle",
        "mayo": "jar",
        "mayonnaise": "jar",
        "meal prep": "bento-box",
        "measuring spoons": "spoon",
        "meat": "cut-of-meat",
        "medicine": "pill",
        "melatonin": "pill",
        "melon": "watermelon",
        "milk": "glass-of-milk",
        "mint": "herb",
        "mints": "candy",
        "mixed nuts": "peanuts",
        "moisturizer": "lotion-bottle",
        "mooncake": "moon-cake",
        "mop": "broom",
        "mouse trap": "mouse-trap",
        "mousetrap": "mouse-trap",
        "mouthwash": "toothbrush",
        "moving boxes": "package",
        "mozzarella": "cheese-wedge",
        "muffin": "cupcake",
        "muffins": "cupcake",
        "mushroom": "mushroom",
        "mushrooms": "mushroom",
        "mustard": "jar",
        "naan": "flatbread",
        "nails": "hammer",
        "napkins": "roll-of-paper",
        "nectarine": "peach",
        "noodles": "spaghetti",
        "nori": "rice-ball",
        "notebook": "notebook",
        "notebooks": "notebook",
        "nutella": "jar",
        "nuts": "peanuts",
        "oat milk": "glass-of-milk",
        "oatmeal": "bowl-with-spoon",
        "oats": "bowl-with-spoon",
        "oil": "pouring-liquid",
        "olive": "olive",
        "olive oil": "olive",
        "olives": "olive",
        "onigiri": "rice-ball",
        "onion": "onion",
        "onions": "onion",
        "orange": "tangerine",
        "orange juice": "tangerine",
        "oranges": "tangerine",
        "oreos": "cookie",
        "packing tape": "package",
        "paella": "shallow-pan-of-food",
        "pain reliever": "pill",
        "pancake mix": "pancakes",
        "pancakes": "pancakes",
        "paper": "notebook",
        "paper clips": "paperclip",
        "paper plates": "fork-and-knife-with-plate",
        "paper towel": "roll-of-paper",
        "paper towels": "roll-of-paper",
        "paperclips": "paperclip",
        "parmesan": "cheese-wedge",
        "parsley": "leafy-green",
        "party": "birthday-cake",
        "party supplies": "balloon",
        "pasta": "spaghetti",
        "pasta sauce": "jar",
        "pastries": "croissant",
        "pastry": "croissant",
        "peach": "peach",
        "peaches": "peach",
        "peanut butter": "honey-pot",
        "peanuts": "peanuts",
        "pear": "pear",
        "pears": "pear",
        "pecans": "peanuts",
        "pen": "pen",
        "pencil": "pencil",
        "pencils": "pencil",
        "penne": "spaghetti",
        "pens": "pen",
        "pepper": "salt",
        "pepperoni": "bacon",
        "peppers": "bell-pepper",
        "pepsi": "cup-with-straw",
        "pet food": "paw-prints",
        "pet supplies": "paw-prints",
        "pho": "steaming-bowl",
        "phone": "mobile-phone",
        "phone case": "mobile-phone",
        "phone charger": "electric-plug",
        "pickled": "jar",
        "pickles": "cucumber",
        "pie": "pie",
        "pie crust": "pie",
        "pineapple": "pineapple",
        "pinto beans": "beans",
        "pistachios": "peanuts",
        "pita": "stuffed-flatbread",
        "pizza": "pizza",
        "pizza dough": "pizza",
        "plant": "potted-plant",
        "plantain": "banana",
        "plants": "potted-plant",
        "plastic cups": "clinking-glasses",
        "plastic utensils": "fork-and-knife",
        "plates": "fork-and-knife-with-plate",
        "plunger": "plunger",
        "pop": "cup-with-straw",
        "popcorn": "popcorn",
        "popsicles": "ice-cream",
        "pork": "cut-of-meat",
        "pork chops": "cut-of-meat",
        "potato": "potato",
        "potato chips": "pretzel",
        "potatoes": "potato",
        "potstickers": "dumpling",
        "potting soil": "potted-plant",
        "power strip": "electric-plug",
        "prawns": "shrimp",
        "pretzel": "pretzel",
        "pretzels": "pretzel",
        "printer paper": "notebook",
        "prosciutto": "bacon",
        "prosecco": "bottle-with-popping-cork",
        "provolone": "cheese-wedge",
        "pudding": "custard",
        "pumpkin pie": "pie",
        "quinoa": "cooked-rice",
        "raisins": "grapes",
        "ramen": "spaghetti",
        "raspberries": "blueberries",
        "razor": "razor",
        "razors": "razor",
        "red apple": "red-apple",
        "red pepper": "bell-pepper",
        "red pepper flakes": "hot-pepper",
        "red wine": "wine-glass",
        "relish": "jar",
        "ribs": "cut-of-meat",
        "rice": "cooked-rice",
        "rice cakes": "rice-cracker",
        "rice crackers": "rice-cracker",
        "roast": "cut-of-meat",
        "rolls": "bread",
        "romaine": "leafy-green",
        "rose": "wine-glass",
        "rosemary": "herb",
        "roses": "bouquet",
        "rotisserie chicken": "poultry-leg",
        "rum": "tumbler-glass",
        "rye bread": "bread",
        "safety pins": "safety-pin",
        "salad": "green-salad",
        "salad dressing": "jar",
        "salad kit": "green-salad",
        "salad mix": "leafy-green",
        "salami": "bacon",
        "salmon": "fish",
        "salsa": "tomato",
        "salt": "salt",
        "salt and pepper": "salt",
        "sandwich": "sandwich",
        "sandwich bread": "bread",
        "sardines": "fish",
        "sauce": "jar",
        "sausage": "bacon",
        "scallions": "onion",
        "school supplies": "notebook",
        "scissors": "scissors",
        "screwdriver": "screwdriver",
        "screws": "nut-and-bolt",
        "scrubber": "sponge",
        "seasoning": "salt",
        "seaweed": "rice-ball",
        "seeds": "potted-plant",
        "seltzer": "cup-with-straw",
        "sewing": "safety-pin",
        "shallots": "onion",
        "shampoo": "lotion-bottle",
        "sharpie": "pen",
        "shaving cream": "razor",
        "shipping": "package",
        "shredded cheese": "cheese-wedge",
        "shrimp": "shrimp",
        "silverware": "fork-and-knife",
        "skewers": "oden",
        "skim milk": "glass-of-milk",
        "smoothie": "bubble-tea",
        "snacks": "pretzel",
        "soap": "soap",
        "soccer ball": "soccer-ball",
        "socks": "socks",
        "soda": "cup-with-straw",
        "soft serve": "soft-ice-cream",
        "sorbet": "ice-cream",
        "soup": "canned-food",
        "soup mix": "steaming-bowl",
        "sourdough": "bread",
        "soy milk": "glass-of-milk",
        "soy sauce": "pouring-liquid",
        "spaghetti": "spaghetti",
        "sparkling water": "cup-with-straw",
        "sparkling wine": "bottle-with-popping-cork",
        "spices": "salt",
        "spinach": "leafy-green",
        "spirits": "tumbler-glass",
        "sponge": "sponge",
        "sponges": "sponge",
        "spoons": "spoon",
        "sports": "soccer-ball",
        "sports drink": "cup-with-straw",
        "sprinkles": "birthday-cake",
        "sprite": "cup-with-straw",
        "sriracha": "hot-pepper",
        "stamps": "envelope",
        "stapler": "paperclip",
        "staples": "paperclip",
        "steak": "cut-of-meat",
        "stew": "pot-of-food",
        "stock": "canned-food",
        "strawberries": "strawberry",
        "strawberry": "strawberry",
        "string cheese": "cheese-wedge",
        "stuffed animal": "teddy-bear",
        "sub": "sandwich",
        "succulent": "potted-plant",
        "sugar": "salt",
        "sunglasses": "sunglasses",
        "sunscreen": "lotion-bottle",
        "sweet potato": "potato",
        "sweets": "candy",
        "swiffer": "broom",
        "swiss cheese": "cheese-wedge",
        "syrup": "honey-pot",
        "taco": "taco",
        "taco seasoning": "taco",
        "taco shells": "taco",
        "tacos": "taco",
        "tamales": "tamale",
        "tangerine": "tangerine",
        "tape": "package",
        "tea": "teacup-without-handle",
        "tea bags": "teacup-without-handle",
        "tea lights": "candle",
        "teapot": "teapot",
        "teddy bear": "teddy-bear",
        "tempura": "fried-shrimp",
        "tequila": "tumbler-glass",
        "thermometer": "thermometer",
        "thyme": "herb",
        "tilapia": "fish",
        "tissues": "roll-of-paper",
        "toast": "bread",
        "toilet bowl cleaner": "toilet",
        "toilet paper": "roll-of-paper",
        "tomato": "tomato",
        "tomato paste": "tomato",
        "tomato sauce": "tomato",
        "tomatoes": "tomato",
        "tools": "screwdriver",
        "toothbrush": "toothbrush",
        "toothpaste": "toothbrush",
        "tortilla chips": "ear-of-corn",
        "tortillas": "burrito",
        "toys": "teddy-bear",
        "trail mix": "peanuts",
        "trash bags": "bucket",
        "tuna": "fish",
        "turkey": "poultry-leg",
        "turkey slices": "meat-on-bone",
        "tv dinner": "bento-box",
        "tylenol": "pill",
        "umbrella": "umbrella",
        "usb cable": "electric-plug",
        "utensils": "spoon",
        "vegetable oil": "pouring-liquid",
        "vegetables": "broccoli",
        "veggies": "broccoli",
        "vinegar": "pouring-liquid",
        "vitamins": "pill",
        "vodka": "tumbler-glass",
        "waffle": "waffle",
        "waffles": "waffle",
        "walnuts": "peanuts",
        "water": "cup-with-straw",
        "watermelon": "watermelon",
        "wheat bread": "bread",
        "whiskey": "tumbler-glass",
        "white bread": "bread",
        "white rice": "cooked-rice",
        "white wine": "wine-glass",
        "whole milk": "glass-of-milk",
        "wine": "wine-glass",
        "wipes": "baby-bottle",
        "wrapping paper": "wrapped-gift",
        "wraps": "burrito",
        "yam": "potato",
        "yerba mate": "mate",
        "yogurt": "bowl-with-spoon",
        "zucchini": "cucumber",
    ]
}

/// The item's icon, or nothing when there isn't one.
struct ItemIconView: View {
    let text: String
    var size: CGFloat = 28
    /// Leaves a little space around the icon in bigger spots (no background).
    var tile = false

    var body: some View {
        if let name = ItemIcon.assetName(for: text) {
            let image = Image(name)
                .resizable()
                .interpolation(.high)
                .scaledToFit()
                .accessibilityHidden(true)
            // No tile or background behind icons; `tile` only adds a little breathing room.
            image
                .frame(width: tile ? size * 0.88 : size, height: tile ? size * 0.88 : size)
                .frame(width: size, height: size)
        }
    }
}

// MARK: - Departments

/// A picture for a list department ("Fruit", "Milk & Dairy"), from the same ItemIcons set.
/// Unlike items, every department gets one: names it doesn't know get a basket.
enum DepartmentIcon {
    static func assetName(for department: String) -> String {
        let key = department.trimmingCharacters(in: .whitespaces).lowercased()
        if let slug = byName[key] { return "ItemIcons/\(slug)" }
        if let match = keywords.first(where: { key.contains($0.word) }) { return "ItemIcons/\(match.slug)" }
        return "ItemIcons/basket"
    }

    /// The server's department names (backend/app/ai/catalog.py), lowercased.
    private static let byName: [String: String] = [
        "fruit": "red-apple",
        "vegetables": "broccoli",
        "flowers & plants": "bouquet",
        "bread & bakery": "bread",
        "milk & dairy": "glass-of-milk",
        "eggs": "egg",
        "cheese": "cheese-wedge",
        "meat & poultry": "cut-of-meat",
        "seafood": "fish",
        "deli & prepared foods": "sandwich",
        "cereal & breakfast": "bowl-with-spoon",
        "syrups & sweeteners": "honey-pot",
        "peanut butter & spreads": "peanuts",
        "baking": "cupcake",
        "spices & seasonings": "salt",
        "oils & vinegar": "olive",
        "condiments & dressings": "jar",
        "pasta & sauce": "spaghetti",
        "rice, grains & beans": "cooked-rice",
        "canned goods & soup": "canned-food",
        "international foods": "steaming-bowl",
        "chips & snacks": "popcorn",
        "nuts & dried fruit": "chestnut",
        "cookies & candy": "cookie",
        "coffee & tea": "hot-beverage",
        "drinks": "cup-with-straw",
        "beer & wine": "wine-glass",
        "frozen foods": "ice",
        "ice cream & frozen desserts": "ice-cream",
        "oral care": "toothbrush",
        "hair care": "lotion-bottle",
        "bath & body": "soap",
        "beauty & cosmetics": "lipstick",
        "medicine & first aid": "adhesive-bandage",
        "vitamins & supplements": "pill",
        "baby": "baby-bottle",
        "paper goods": "roll-of-paper",
        "cleaning & laundry": "sponge",
        "pet supplies": "paw-prints",
        "batteries & light bulbs": "battery",
        "kitchen & home": "fork-and-knife",
        "electronics": "headphone",
        "office & school": "pencil",
        "clothing": "socks",
        "toys & games": "teddy-bear",
        "tools": "screwdriver",
        "hardware & fasteners": "nut-and-bolt",
        "paint": "bucket",
        "plumbing": "plunger",
        "electrical": "electric-plug",
        "lumber & building materials": "hammer",
        "garden & outdoor": "potted-plant",
    ]

    /// For other names, like ones typed into an item's details. First match wins.
    private static let keywords: [(word: String, slug: String)] = [
        ("produce", "leafy-green"), ("fruit", "red-apple"), ("vegetable", "broccoli"), ("veggie", "broccoli"),
        ("bakery", "bread"), ("bread", "bread"), ("dairy", "glass-of-milk"), ("milk", "glass-of-milk"),
        ("egg", "egg"), ("cheese", "cheese-wedge"), ("poultry", "poultry-leg"), ("meat", "cut-of-meat"),
        ("seafood", "fish"), ("fish", "fish"), ("deli", "sandwich"), ("ice cream", "ice-cream"),
        ("frozen", "ice"), ("snack", "popcorn"), ("candy", "lollipop"), ("coffee", "hot-beverage"),
        ("drink", "cup-with-straw"), ("beverage", "cup-with-straw"), ("pantry", "canned-food"),
        ("canned", "canned-food"), ("household", "roll-of-paper"), ("paper", "roll-of-paper"),
        ("clean", "sponge"), ("pet", "paw-prints"), ("baby", "baby-bottle"), ("party", "balloon"),
        ("health", "adhesive-bandage"), ("beauty", "lipstick"), ("garden", "potted-plant"),
    ]
}

/// A department's picture, sized for headings.
struct DepartmentIconView: View {
    let department: String
    var size: CGFloat = 18

    var body: some View {
        Image(DepartmentIcon.assetName(for: department))
            .resizable()
            .interpolation(.high)
            .scaledToFit()
            .frame(width: size, height: size)
            .accessibilityHidden(true)
    }
}
